# Generated by Django 5.0.4 on 2024-04-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_latitude_movie_longitude_alter_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
